{
    "openapi": "3.0.0",
    "info": {
        "title": "",
        "description": "",
        "version": ""
    },
    "components": {
        "securitySchemes": {
          "BearerAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT"
          }
        }
      },
      "security": [
        {
          "BearerAuth": []
        }
      ], 
    "consumes": [
        "application/json"
    ],
    "paths": {
        "/api/users/candidatures": {
            "get": {
                "summary": "mes candidatures",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Candidatures"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "Authorization",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/acceptees": {
            "get": {
                "summary": "Lister les candidatures d'un candidat en particulier",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Candidatures"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/refusees": {
            "get": {
                "summary": "lister les candidatures refus√©es ",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Candidatures"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/en_attente": {
            "get": {
                "summary": "lister les candidatures en attente ",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Candidatures"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/refuser": {
            "put": {
                "summary": "Refuser une candidature",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Candidatures"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/accepter": {
            "put": {
                "summary": "Accepter une candidature",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Candidatures"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/candidatures": {
            "post": {
                "summary": "ajouter une candidature ",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Candidatures"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "Authorization",
                        "type": "string"
                    }
                ]
            }
        },
        "/": {
            "get": {
                "summary": "lister une formation en particulier",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Formations"
                ],
                "parameters": [
                    {
                        "in": "query",
                        "name": "",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "Authorization",
                        "type": "string"
                    }
                ]
            },
            "delete": {
                "summary": "Supprimer un role",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Utilisateurs"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            },
            "post": {
                "summary": "modifier une formation",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Formations"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            },
            "put": {
                "summary": "modifier les infos  d'un candidat",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Utilisateurs"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "nom": "string",
                                    "prenom": "string",
                                    "adresse": "string",
                                    "telephone": "string",
                                    "email": "string",
                                    "password": "string"
                                }
                            },
                            "example": {
                                "nom": "benjamin",
                                "prenom": "kayunga aussi",
                                "adresse": "mermoz",
                                "telephone": "715223581",
                                "email": "magid1@gmail.com",
                                "password": "Paasemoi15@"
                            }
                        }
                    }
                }
            }
        },
        "/api/candidatures": {
            "get": {
                "summary": "Lister toutes le candidatures",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Candidatures"
                ],
                "parameters": [
                    {
                        "in": "query",
                        "name": "",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/formation": {
            "post": {
                "summary": "Ajouter une formation",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Formations"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/formations": {
            "get": {
                "summary": "Liste des formations",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Formations"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/roles": {
            "post": {
                "summary": "Ajouter un role",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Utilisateurs"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/refresh_token": {
            "post": {
                "summary": "regenerer le token",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Utilisateurs"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "Authorization",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/logout": {
            "get": {
                "summary": "se deconnecter ",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Utilisateurs"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    },
                    {
                        "in": "header",
                        "name": "Authorization",
                        "type": "string"
                    }
                ]
            }
        },
        "/api/login": {
            "post": {
                "summary": "connecter un utilisateur",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Utilisateurs"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "email": "string",
                                    "password": "string"
                                }
                            },
                            "example": {
                                "email": "bamagid60@gmail.com",
                                "password": "Paasemoi15@"
                            }
                        }
                    }
                }
            }
        },
        "/api/users": {
            "post": {
                "summary": "inscrire un candidat",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Utilisateurs"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "nom": "string",
                                    "prenom": "string",
                                    "adresse": "string",
                                    "telephone": "string",
                                    "email": "string",
                                    "password": "string"
                                }
                            },
                            "example": {
                                "nom": "benjamin",
                                "prenom": "kayunga le boss",
                                "adresse": "mermoz",
                                "telephone": "715223581",
                                "email": "magid1@gmail.com",
                                "password": "Paasemoi15@"
                            }
                        }
                    }
                }
            }
        },
        "/api/admin": {
            "post": {
                "summary": "inscrire un admin",
                "description": "",
                "produces": [
                    "application/json"
                ],
                "responses": {
                    "200": {
                        "examples": {
                            "application/json": ""
                        }
                    }
                },
                "tags": [
                    "Utilisateurs"
                ],
                "parameters": [
                    {
                        "in": "header",
                        "name": "User-Agent",
                        "type": "string"
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "properties": {
                                    "nom": "string",
                                    "prenom": "string",
                                    "adresse": "string",
                                    "telephone": "string",
                                    "email": "string",
                                    "password": "string"
                                }
                            },
                            "example": {
                                "nom": "bah",
                                "prenom": "binta",
                                "adresse": "mermoz",
                                "telephone": "715223581",
                                "email": "binta@gmail.com",
                                "password": "Paasemoi15@"
                            }
                        }
                    }
                }
            }
        }
    }
}